/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sma_ihm;

/**
 *
 * @author mathieu
 */
@SuppressWarnings("serial")
public class ControlePanel extends javax.swing.JPanel {

	private SystemPanel pere;
    /**
     * Creates new form ControlePanel
     */
    public ControlePanel(SystemPanel parent) {
        initComponents();
        pere = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startBouton = new javax.swing.JButton();
        stopBouton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Controle"));

        startBouton.setText("Start");
        startBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	stopBoutonActionPerformed(evt);
            }
        });

        stopBouton.setText("Stop");
        stopBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	startBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startBouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(stopBouton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBouton)
                    .addComponent(stopBouton))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void startBoutonActionPerformed(java.awt.event.ActionEvent evt) {   
    	
    }   
    
    private void stopBoutonActionPerformed(java.awt.event.ActionEvent evt) {                                         
		pere.lancerApplication();
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startBouton;
    private javax.swing.JButton stopBouton;
    // End of variables declaration//GEN-END:variables
}
